### ISSUE TITLE
Lab7

### ISSUE THREAD

**Issue by JulianIsFree** [Evgueni-Petrov-aka-espetrov/TestDriver#5]
На третий тест некорректно создается in.txt
[in.txt](https://github.com/Evgueni-Petrov-aka-espetrov/TestDriver/files/4676013/in.txt)
[Debug.zip](https://github.com/Evgueni-Petrov-aka-espetrov/TestDriver/files/4676016/Debug.zip)
[out.txt](https://github.com/Evgueni-Petrov-aka-espetrov/TestDriver/files/4676012/out.txt)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
В третьем тесте всё ок.
Что делать для такого in.txt, однозначно написано в todo.txt
