### ISSUE TITLE
Useless timing '0 ms'

### ISSUE THREAD

**Issue by dbakshee** [Evgueni-Petrov-aka-espetrov/TestDriver#9]
At [this place](https://github.com/Evgueni-Petrov-aka-espetrov/TestDriver/blob/39e2debacd9ab2511fa6b502a759ec31edc0d762/testDriver.c#L90) test driver measures CPU time taken by `system` to launch the lab, not the time taken by the lab itself. So the time reported is confusing, or useless at least. It mostly shows '0 ms'

Correct timing should should measure the CPU time of the child process.

This is  what I see on mac osx.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Fixed by https://github.com/Evgueni-Petrov-aka-espetrov/TestDriver/pull/11
